/**
 * Community API
 * Documentation Community API v1.0
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Community {
    id?: string
    name?: string
    cityCode?: string
}
