/**
 * Community API
 * Documentation Community API v1.0
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from "@angular/common/http"

import { Observable } from "rxjs"

import { Community } from "../model/models"

import { Configuration } from "../configuration"

export interface CommunityControllerServiceInterface {
    defaultHeaders: HttpHeaders
    configuration: Configuration

    /**
     *
     *
     * @param community
     */
    createCommunity(
        community: Community,
        extraHttpRequestParams?: any
    ): Observable<object>

    /**
     *
     *
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<Community>>

    /**
     *
     *
     * @param id
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<object>
}
